---
- hosts: 192.168.151.166
  tasks:
    - name: Disable plugin discovery and auto-download by setting plugin_paths
      community.general.terraform:
        project_path: '{{ project_dir }}'
        state: "{{ state }}"
        force_init: true
        plugin_paths:
          - '{{ plugin_dir }}'
